name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:    # Allows you to run it manually

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream
    steps:
      # Step 1: Checkout your fork's main branch
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      # Step 2: Sync from ginilmathew
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_repository: ginilmathew/pillipot-webapp
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
