name: Upstream Sync

permissions:
  contents: write

on:
  repository_dispatch:
    types: [upstream_updated] # This matches the signal from Step 3
  workflow_dispatch:          # Keep this so you can still run it manually

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: ginilmathew/pillipot-webapp
          upstream_sync_branch: main
          test_mode: false
