name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *" # Runs roughly every 15 minutes
  workflow_dispatch:    # Allows you to run it manually

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: ginilmathew/pillipot-webapp
          upstream_sync_branch: main
          test_mode: false
